### ISSUE TITLE
Throwing away PC is unnecessary

### ISSUE THREAD

**Issue by MartinZikmund** [j-lord/zen#3]
I understand you prefer Mac, but throwing away the PC is unnecessary now that there is [Linux subsystem on Windows](https://msdn.microsoft.com/en-us/commandline/wsl/about).

Maybe you could update the guide with this 👍 ?

**Comment by j-lord** [comment]
Maybe eventually, as of now, I can't make the assumption that everyone has updated to the most recent version of Windows.
